apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgvector
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgvector
    template:
      type: Opaque
      engineVersion: v2
      data:
        user: '{{ .user }}'
        password: '{{ .password }}'
        host: '{{ .host }}'
        port: '{{ .port }}'
        dbname: '{{ .dbname }}'
        jdbc-uri: '{{ printf "jdbc:postgresql://%s.%s:%s/%s?password=%s&user=%s" .Values.secret.host
          (include "pgvector.namespace" .) .Values.secret.port .Values.secret.dbname
          .Values.secret.password .Values.secret.user | b64enc | quote }}'
        uri: '{{ printf "postgresql://%s:%s@%s.%s:%s/%s" .Values.secret.user .Values.secret.password
          .Values.secret.host (include "pgvector.namespace" .) .Values.secret.port
          .Values.secret.dbname | b64enc | quote }}'
  data:
  - secretKey: user
    remoteRef:
      key: secret/data/hub/pgvector
      property: user
  - secretKey: password
    remoteRef:
      key: secret/data/hub/pgvector
      property: password
  - secretKey: host
    remoteRef:
      key: secret/data/hub/pgvector
      property: host
  - secretKey: port
    remoteRef:
      key: secret/data/hub/pgvector
      property: port
  - secretKey: dbname
    remoteRef:
      key: secret/data/hub/pgvector
      property: dbname
  - secretKey: jdbc-uri
    remoteRef:
      key: secret/data/hub/pgvector
      property: jdbc-uri
  - secretKey: uri
    remoteRef:
      key: secret/data/hub/pgvector
      property: uri
  - secretKey: jdbc-uri
    remoteRef:
      key: secret/data/hub/pgvector
      property: jdbc-uri
  - secretKey: uri
    remoteRef:
      key: secret/data/hub/pgvector
      property: uri
